language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

sudo: true

cache:
  apt: true
  directories:
    - ~/.m2

install:
    - git clone https://github.com/renespeck/knowledgeextraction
    - cd knowledgeextraction
    - mvn compile install

script: mvn clean compile --quiet -DskipTests=false
