language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

sudo: true

cache:
  apt: true
  directories:
    - ~/.m2

install:
    - true

script: mvn clean compile --quiet -DskipTests=false
